---
#noqa: name[play]
- import_playbook:  "{{ playbook_dir }}/deploy/undeploy_cf_servers.playbook.yml"
#noqa: name[play]
- import_playbook:  "{{ playbook_dir }}/deploy/undeploy_gw_servers.playbook.yml"
