---
#noqa: name[play]
- import_playbook: "{{ playbook_dir }}/downloader/product_download_installers.playbook.yml"
#noqa: name[play]
- import_playbook: "{{ playbook_dir }}/deploy/copy_cf_package_to_host.yml"
#noqa: name[play]
- import_playbook: "{{ playbook_dir }}/deploy/deploy_cf_servers.playbook.yml"
